services:
  php:
    build: .
    container_name: php
    volumes:
      - ./builder:/var/www/html
    ports:
      - "8078:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3366:3366"